const predefinedTags = [
    // Tech & Code
    'Tech',
    'Programming',
    'JavaScript',
    'TypeScript',
    'Python',
    'Rust',
    'Go',
    'Web Dev',
    'Mobile Dev',
    'Frontend',
    'Backend',
    'Fullstack',
    'DevOps',
    'APIs',
    'Cloud',
    'Machine Learning',
    'AI',
    'Data Stuff',
    'Cybersecurity',
    'Blockchain',
    'Databases',
  
    // Professional / Work
    'Career',
    'Remote Work',
    'Freelancing',
    'Startups',
    'Tech Industry',
    'Job Hunt',
    'Networking',
    'Open Source',
    'Internships',
    'Interviews',
    'Leadership',
    'Deadlines',
    'Teamwork',
    'Burnout Culture',
    'Meetings That Could Be Emails',
    'Micromanagement',
  
    // Personal & Relatable
    'College',
    'Rant',
    'Side Projects',
    'Burnout',
    'Impostor Syndrome',
    'Overthinking',
    'Productivity',
    'Procrastination',
    'All-Nighters',
    'Learning Stuff',
    'Mental Health',
    'Coding Journey',
    'Work-Life Balance',
    'I Don’t Know What I’m Doing',
    'Motivation Struggles',
    'Tired But Inspired',
    'Surviving Deadlines',
    'Lowkey Panicking',
  
    // Meme / Chaos / Humor
    'Dark Mode Only',
    'Tabs vs Spaces',
    'Stack Overflow Therapy',
    'Console.Log-Driven Dev',
    'Why Is This Not Working',
    'Built At 3AM',
    'Oops Broke Prod',
    'Git Blame',
    'Commit Regrets',
    'Friday Deploys',
    'Merge Conflicts',
    'Rubber Duck Debugging',
    'AI Wrote This',
    'npm install pain',
    'Hotfix Incoming',
    'Bug or Feature?',
    'Code Works Don’t Touch',
    'Tech Twitter',
    'Zoom Fatigue',
    'Sleep Is For Losers',
    'Caffeine-First Workflow',
    'Brain.exe Crashed',
    'It Worked Yesterday',
  
    // Meta / Tone
    'Hot Take',
    'Deep Dive',
    'Beginner Friendly',
    'Unfiltered',
    'Throwback',
    'Mini Rant',
    'Code Dump',
    'Shower Thoughts',
    'Late Night Thoughts',
    'Life Update',
    'Story Time',
    'Lessons Learned',
  ];
  
  module.exports = { predefinedTags };  